# ---------------------------------------------------------
# The Gradle build expands its project properties to
# replace the substitution tokens.
# ---------------------------------------------------------

# shown on the actuator /info endpoint
info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}
    java:
      source: ${sourceCompatibility}
      target: ${targetCompatibility}

# changes actuator endpoints - /manage/info
management:
  context-path: "/manage"

api:
  context-path: "/api"

# cache expiration for things like workflow status
cache:
  expirationSeconds: 30

security:
  basic:
    enabled: \${SECURITY_ENABLED:true}

spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false
    mapper:
      sort_properties_alphabetically: true
  session:
    enabled: \${SESSION_CLUSTER_ENABLED:true}
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: \${DB_USER}
    password: \${DB_PASSWORD}
    validationQuery: "SELECT 1"
    max-active: 2
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
  http:
    multipart:
      location: \${java.io.tmpdir}
      maxFileSize: "1000MB"
      maxRequestSize: "1000MB"

itembank:
  systemVersion: "iat-41"
  localBaseDir: \${HOME}/ItemBank
  itemBankViewerUrl: "http://itemreview.smarterbalanced.org/iris/Pages/item.xhtml?bankId=\${itembank.bankKey}&type=%s&id=%s"
  systemUser:
    userName: "iat-bulk@smarterbalanced.org"
    fullName: "Item Bulk Management Service"
  enabled:
    broker: true
    database: true
    producer: true
  services:
    permission:
      url: "http://localhost:8182"
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: \${GITLAB_GROUP}
    versionedBucketName: \${GITLAB_GROUP}-versioned
    accessKey: \${IAT_AWS_ACCESS_KEY}
    secretKey: \${IAT_AWS_ACCESS_SECRET}
  events:
    queue:
      queueName: "iat_item_event_queue"
    errorQueue:
      queueName: "iat_item_event_queue.dlq"
  itemBulkUpdate:
    events:
      requestQueue:
        queueName: "iat.item.bulk.update.request"
      responseQueue:
        queueName: "iat.item.bulk.update.response"
      errorQueue:
        queueName: "iat.item.bulk.update.dlq"
    asl:
      sendResponseEvery: 2
      exclusionPatterns:
        - "**/__MACOSX/**"

tasks:
  itemCleanupThresholdMillis : "7200000"
  itemCleanupRunEveryMillis: "7200000"